# Generated by Django 4.0.3 on 2022-10-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='time_updatee',
        ),
        migrations.AddField(
            model_name='women',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
